### ISSUE TITLE
Issues with Geolocation API

### ISSUE THREAD

**Issue by cj81499** [felixhageloh/uebersicht#105]
I'm having issues with making [this widget](http://www.mediafire.com/download/ya04sfdjah7i4zk/index.coffee) use the Geolocation API.

Can someone help me set it up so the location changes?

I have very little coding knowledge, but if you could try explain how to add it, that would be great.

**Comment by farski** [comment]
The geolocation support is fairly experimental at this point. I didn't look at your specific code because I didn't want to download a mystery file (maybe post it as a gist?), but if you want to look at how I handle it some cases, look at this: https://gist.github.com/farski/d874e59841001cc399f1

Essentially in the `afterRender` function, I register hanlders on the `watchPosition` and `getCurrentPosition` callbacks (those are what's coming from the web API). Because those callbacks can end up getting called a _lot_, I don't actually do any work in those handlers, I just update the command being run on the normal frequency with a new position.

This may not be the right way to handle it in all cases, for it's on approach.

**Comment by cj81499** [comment]
Here it is as a gist. I could really use some widget specific help. 

https://gist.github.com/anonymous/c0e0d84800f6a199329f

**Comment by cj81499** [comment]
Here it is as a gist.

https://github.com/felixhageloh/uebersicht/issues/105

**Comment by cj81499** [comment]
Here it is as a gist. 

https://gist.github.com/anonymous/c0e0d84800f6a199329f

**Comment by farski** [comment]
@cj81499 was there anything you couldn't figure out from my example?

**Comment by cj81499** [comment]
@farski I just don't understand how I can incorporate it into my widget.
