### ISSUE TITLE
Fix on desktop?

### ISSUE THREAD

**Issue by eelkeblok** [felixhageloh/uebersicht#107]
Sorry, newbie here.

Maybe I'm doing something wrong, but when I was initially extremely excited to move from NerdTool over to übersicht, I am now running into an issue. With NerdTool, I could hit cmd-f3 to hide all windows and reveal the desktop with the NerdTool widgets. I did that when running ubersicht and at first thought it didn't work, but then I realized cmd-f3 is simply hiding the ubersicht "window" as well. 

Am i doing something wrong? Is there a small tweak to my workflow to have it work the intended way (i.e. quickly reveal the desktop and the widgets)?

**Comment by felixhageloh** [comment]
If you have your interaction shortcut key set to cmd (I believe that is the default) then cmd-f3 won't work since it temporarily brings the window to the foreground. Once it is in the foreground it gets hidden like any other window.
There is two solutions: 

- you can set the interaction shortcut to something else (of disable it when you are not using it)
- you can use the trackpad gesture instead of cmd-f3

Hope this helps!

**Comment by eelkeblok** [comment]
Thanks a lot, that was it. Stupid I didn't consider changing the interaction key setting (which I did notice, but somehow didn't think would be related).

**Comment by felixhageloh** [comment]
No problem - also not super happy about this aspect of the app!
