### ISSUE TITLE
App Nap

### ISSUE THREAD

**Issue by cj81499** [felixhageloh/uebersicht#109]
Is there any way to make Übersicht activate App Nap on a per widget basis? This could help lower battery usage for those of us on laptops with lots of widgets.

**Comment by felixhageloh** [comment]
It's not possible at the moment; also I'm not sure whether apple provides a fine grained API for App Nap that would make this possible. From what I understand, app nap works on a window basis and since all widgets live in the same window it would not be possible to do this on a per widget basis - at least not easily
