### ISSUE TITLE
@keyframes declaration is weird

### ISSUE THREAD

**Issue by Baxter900** [felixhageloh/uebersicht#111]
So I've been trying to animate with `@keyframes`, and I run into a weird issue. I've been using the workaround as stated here: https://github.com/felixhageloh/uebersicht/issues/35
However, I can't have an `@keyframes` declared in more than one widget, and if I put all the declarations into one widget, then it only loads when I save the widget in question.

So an example, I have in one widget the code:
```html
   <style>
    @-webkit-keyframes float1{
       from{top: 0px}
       to{top: 80px}
     }
    @-webkit-keyframes float2{
       from{top: 60px}
       to{top: 0px}
    }
    @-webkit-keyframes float3{
       from{top: 0px}
       to{top: 40px}
    }
    @-webkit-keyframes float4{
       from{top: 20px}
       to{top: 0px}
    }
    @-webkit-keyframes float5{
       from{top: 0px}
       to{top: 10px}
    }
  </style>
```
I wanted to put similar code in a separate widget:
```html
 <style>
    @-webkit-keyframes floatWeather{
       from{top: 310px}
       to{top: 300px}
    }
  </style>
```
But that doesn't work, when I run this nothing happens:
```style
  animation-iteration-count: infinite
  animation-timing-function: ease
  animation-direction: alternate
  animation-name: floatWeather
  animation-duration: 3s
```

If I make it so the first widget has this:
```html
  <style>
    @-webkit-keyframes float1{
       from{top: 0px}
       to{top: 80px}
    }
    @-webkit-keyframes float2{
       from{top: 60px}
       to{top: 0px}
    }
    @-webkit-keyframes float3{
       from{top: 0px}
       to{top: 40px}
    }
    @-webkit-keyframes float4{
       from{top: 20px}
       to{top: 0px}
    }
    @-webkit-keyframes float5{
       from{top: 0px}
       to{top: 10px}
    }
    @-webkit-keyframes floatWeather{
       from{top: 310px}
       to{top: 300px}
    }
  </style>
```
Then when I run this **and save the widget** it works fine:
```style
  animation-iteration-count: infinite
  animation-timing-function: ease
  animation-direction: alternate
  animation-name: floatWeather
  animation-duration: 3s
```
However, if I don't save the widget, i.e. when my computer boots up and Übersicht opens, then the animation doesn't run. I understand that this is because by using the `<style>` tag, I'm ignoring the sandboxing of the widgets, but I can't figure out why it's happening in this way.

Anyway, might be a bug, or it might just be that I'm missing something, either way, thanks for making Übersicht!

**Comment by felixhageloh** [comment]
Haven't tried this, but I imagine the issue is that the widget style, where you set `animation-name: floatWeather`, is applied _before_ the `<style>` tag renders. This means, at that point there is no keyframe animation called 'floatWeather' defined yet and it fails. It does get defined an instant later tho, which is why when you hit save and the widget refreshes it starts working - it still has the keyframes definition from the previous render. 
If my theory is correct, then you could try using inline styles like this:

``` coffeescript
render: -> """
  <style>
    @-webkit-keyframes floatWeather {
      ...
    }
  </style>
  <div style="animation-name: floatWeather ">
    ...
  </div>
"""
```

Where `<div>` is the element that you want to apply the animation to. That way you ensure that the keyframes definition is present when you apply it.

**Comment by Baxter900** [comment]
Nope, that didn't work. Also, I said this before but I think you missed it (explaining things is not my strong point ^_^;) but if I declare the keyframes in the widget I want animated, it doesn't work, even after I save the file. Instead, I have to put the keyframes declarations in another widget (the widget is called background.widget, so it probably loads first due to alphabetical order, and in that one it also works fine when I declare the keyframes within the widget), **then** I have to save the widget (not the background widget, the other one) and then it animates.

It's really a weird interaction. Anyway, thanks for trying to help me, hopefully we can figure this out.

**Comment by felixhageloh** [comment]
I see - thanks for explaining in more detail. 
Could you maybe send the two widgets in question? Hard to judge whether something else is happening here.

**Comment by Baxter900** [comment]
Sure, here are two widgets, the one background one, in which the animation works properly and is declared within it and works perfectly as expected, and the weather widget, which is the one with the weird loading.

I did a little more testing so I can save you some time on a few things that weren't true. It's not alphabetical order, if background.widget is x.widget, it still loads fine. It's also not because in background.widget the animation is being assigned to classes, and in the other widget I'm using the base class to apply it to everything, if I make classes within the other widget then apply it only to those in the identical way as in background.widget, it doesn't fix it. I couldn't think of anything else that could be the problem after that.

Anyway, hopefully you can figure this out, I'm at a loss, here's the widgets: https://www.dropbox.com/s/dowfmjzuqg7p1q1/Animation%20Widgets.zip?dl=0

**Comment by Baxter900** [comment]
Just curious, any news on this? I'd like to push the package so other people can use it, but I wanted to include a zipped file with a couple of the top packages reskinned to match with the background, layered and floating among it as the end result is quite cool. If it just plain won't work I'll push the background without them, but was just curious.

In any news, no rush. Take your time.

**Comment by felixhageloh** [comment]
Hey, sorry - I've been crazy busy recently! 
So I had a quick look and i think I found the issue. I think the problem is that you apply the animation to the outer widget element (i.e. the widget itself). However, the style tag get's inserted _inside_ the widget as you can see here:

![screen shot 2015-06-22 at 9 03 33](https://cloud.githubusercontent.com/assets/367503/8277041/5d805a64-18be-11e5-8c57-82789c79a322.png)

I'm not 100% sure why this is an issue. It looks like the keyframe definition is not reachable because it is defined in a child element of the dom element you try to apply it to. The reason I think that is that if you apply the animation to the `.main` element, it works fine:

```
  .main
    position: relative
    animation-iteration-count: infinite
    animation-timing-function: ease
    animation-direction: alternate
    animation-name: floatWeather
    animation-duration: 3s
```

and the animation changed to:

```
<style>
    @-webkit-keyframes floatWeather{
       from{top: 10px}
       to{top: 0px}
    }
</style>
```

And obviously, having a style tag that is inserted in the dom later (like with the background widget) also works, so it looks like the only scenario were it doesn't work is, if the style tag is a child node of the element that you are trying to animate. I'm also not sure whether this is on purpose or just a WebView bug or just undefined behavior in the CSS spec. 

In any case, the solution of applying it to the `.main` element works and I think it is even better, since you don't have to change the keyframe definition whenever you change the position of your widget!

**Comment by Baxter900** [comment]
Thanks! That worked. Sorry for taking up your time so much, but thank you!
