### ISSUE TITLE
Image anchored at center rather than top left?

### ISSUE THREAD

**Issue by travtrigs** [felixhageloh/uebersicht#119]
When you set the position of an image element, that position is always the top left corner of the image. Is there a way to position an image such that that coordinate is in the center of the image? For example, this is how images currently get positioned with Top = 0px and Left = 0px:
<img width="190" alt="screen shot 2015-08-09 at 1 35 23 pm" src="https://cloud.githubusercontent.com/assets/13620298/9156067/8a0bcb2e-3e9b-11e5-98b4-441a5c1e8bf0.png">
And this is how I'd like to position them with top and left still being 0:
<img width="161" alt="screen shot 2015-08-09 at 1 35 27 pm" src="https://cloud.githubusercontent.com/assets/13620298/9156068/900792f6-3e9b-11e5-935b-fb25c63c07bf.png">
I know I could just make the position be -5px top and -5 left for a 10x10 px image to achieve a similar effect, but for the widget I'm currently making it would be much easier to be able to have the positions at 0,0 and have it center around that.

**Comment by zanderp** [comment]
I think that what you suggest is not quite a good idea because:
1. Ubersicht tries to be like a stripped version of a browser
2. As most of the European/US people write from left to right the basic alignment starts from left to right. 
3. As far as I know there is no web programming style that native will let you align from the middle of the selected area.

It can be done but not good to implement for all the people.

**Comment by felixhageloh** [comment]
@travtrigs the usual trick is to set a negative margin 

```css
margin-left: -(width / 2)px
margin-top: -(height / 2)px
```
(you will have to substitute width/2 and height/2 with actual numbers)

Now that way, `top` and `left` control the position of the center of the image

**Comment by soberstadt** [comment]
I'd also check out this guild: https://css-tricks.com/centering-css-complete-guide/ it has both flexbox and non-flexbox options for centering elements of an unknown height and width.
