### ISSUE TITLE
High CPU usage since update to 0.7.23

### ISSUE THREAD

**Issue by herrbischoff** [felixhageloh/uebersicht#159]
Since updating Übersicht to 0.7.23, I notice a dramatic increase of CPU usage. The processes `Übersicht` and `localnode` combined are responsible for taking more than 60% of my CPU. The current energy impact is 67,5 — far more than any other application:

<img width="529" alt="screen shot 2016-01-21 at 18 15 07" src="https://cloud.githubusercontent.com/assets/8957346/12488304/385ea600-c06b-11e5-99d6-8c491df9c9af.png">

My MacBook Pro is running hot due to this. The update coincided with the OS X 10.11.3 update, maybe something is amiss there. Disabling all widgets has no effect on CPU consumption, so Übersicht itself must be at fault here.

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.3
BuildVersion:	15D21
```

Let me know if you need any more information.

**Comment by herrbischoff** [comment]
Nevermind, I found the issue myself. There was one pesky widget that hid from myself with `refreshFrequency: 0` set. I guess Übersicht was just trying to do its best refreshing it more than one time every millisecond. Considering the effort, about 60% CPU doesn't sound so bad after all. ;)

**Comment by hawkrives** [comment]
@felixhageloh Should Übersicht treat `refreshFrequency: 0` as `refreshFrequency: false`?

**Comment by soberstadt** [comment]
I thought that's what it was supposed to be.

**Comment by herrbischoff** [comment]
In my opinion `0` should absolutely turn off refresh instead of running as fast as possible.

**Comment by hawkrives** [comment]
Right, so it turns out that in JS, `0 !== false`. Which is very interesting.

So, here, for example, at [widget.coffee#L105], we have 

```coffee
return if api.refreshFrequency == false
```

which is compiled into 

```js
if (api.refreshFrequency === false) {
  return;
}
```

which is not executed for `refreshFrequency: 0`. 

We'd probably need to change both [widget.coffee#L105] and [widget.coffee#L160].


[widget.coffee#L105]: https://github.com/felixhageloh/uebersicht/blob/master/server/src/widget.coffee#L105
[widget.coffee#L160]: https://github.com/felixhageloh/uebersicht/blob/master/server/src/widget.coffee#L160

**Comment by felixhageloh** [comment]
I can't remember if is this new behavior new since the support for string refresh frequencies. If it is then it would be an easy decision to just revert it to the old behavior. 

If it is not I would vote for leaving it as is. It might seem counter intuitive at first, but if you think about it, the refresh frequency defines the delay between each update. I the delay is 0 it means: don't wait between updates and update as fast as you can. 

OTH, you could say that's not behavior anyone would want - I'm not sure. What are your thoughts? Also does anyone remember if this was always the case?

**Comment by hawkrives** [comment]
I don't think that it's changed with the string frequencies, since it only kicks in if `refreshFrequency` is a string:

```coffee
if typeof implementation.refreshFrequency is 'string'
  implementation.refreshFrequency = ms(implementation.refreshFrequency)
```

I must admit that I cannot think of any reasons why I would want to set `refreshFrequency: 0`.

**Comment by herrbischoff** [comment]
Thinking further about it, the update to 0.7.23 was probably very close to activating that pesky widget. So I guess it was just the widget's fault. Since removing the `0`, everything works as expected. Since @felixhageloh votes for leaving it as is, this issue is resolved for me and I will close it.
