### ISSUE TITLE
Ubersicht sends out a trickle of data that wreaks havoc on data caps.

### ISSUE THREAD

**Issue by Trapper777** [felixhageloh/uebersicht#164]
According to a post I received on a little fan forum, and just looking on my own Activity Monitor, ubersicht sends a ton of data (from what you'd expect) away from the computer.

According to one user:

> 48 hours after installing Ubersicht I notice Data Out has jumped nearly 15GB

And that

> Ubersicht is transmitting something, slow and steady, I don't know what.

First, whatever's being transmitted, it wreaks havoc on the data caps used by many people in places with less internet access (like the entire continent of Australia). Second of all, what data is it sending? I have nothing but a Calendar widget and it's sending a shocking amount of data out. The refresh rate is set in the range of hours. That seems almost suspicious.

**Comment by felixhageloh** [comment]
I can assure you that Übersicht itself is not sending any data over the internet. Widgets can send data of course (for example weather widgets etc.), but your are saying that you are seeing the same thing with just the Calendar Widget installed. 

I'm not sure were you are seeing the data being sent, but if you check the Network tab inside Activity Monitor you _will_ see data being sent. This is because Übersicht is basically a client-server web app. It runs a node.js server in the background and the UI is essentially just a large transparent Safari window stuck to your desktop. However, this data is sent over your _local_ network only (and on top of that, only from and to the same machine). 

So it should not affect or show up in your internet usage. Again, the only exception are widgets that need to send and receive data over the internet by design. 

Please let me know what you are seeing doesn't match up with my explanation here and I will look further into it!

**Comment by Trapper777** [comment]
Ok, that makes sense! Thanks. I was a little worried there.

**Comment by felixhageloh** [comment]
:+1:
