### ISSUE TITLE
Ubersicht 0.8 falls over quickly, mistakes some folders as widgets including all node_modules JS files

### ISSUE THREAD

**Issue by edasque** [felixhageloh/uebersicht#171]
I installed the latest version and while it first displays my widget it then fails to respond. From what I can see, it's seeing too many things as widgets, maybe going into the different node_modules directories, the list of widgets I see is gigantic before it fails to respond.

<img width="382" alt="banners_and_alerts" src="https://cloud.githubusercontent.com/assets/219187/13256483/ef7b9106-da18-11e5-9a96-612f0dd562e5.png">

**Comment by felixhageloh** [comment]
I think this is not a new issue, but made more apparent by the addition of the widget list in the status menu. Basically, at the moment Übersicht needs to treat every js and coffee file as a potential widget, because there is no naming convention (yet). Pre version 0.8, if it couldn't 'parse' the file as a widget it would just fail, print an error message in the console and be done with it; which is probably why this worked out fine so far. 
Now I'm showing any potential widget in the menu bar because I can't tell whether it the js file is a widget with a syntax error, or not meant to be a widget at all. The idea was that soon I can also highlight widgets with syntax errors in the menu and maybe even show error messages there to allow for easier debugging. 

So essentially this is not really a bug but a design decision/mistake(?). I'll have to think a bit more about solution for this - suggestions welcome of course!

Btw, out of curiosity, how do you include these npm modules in your widgets at the moment?

**Comment by edasque** [comment]
the npm modules are used in the scripts, not the widgets so there is a node_modules directory in most of my script directories. While this issue didn't hurt until this newest version, it does completely freeze my Uebersicht, I can't use it at all anymore.

Wouldn't widgets only be at the root of the widget folder? In 0.8, ~/widgets_folder/widget1.widget/scripts/node_modules/lodash.js is being seen as a widget.

**Comment by Pe8er** [comment]
> So essentially this is not really a bug but a design decision/mistake(?). I'll have to think a bit more about solution for this - suggestions welcome of course!

How about showing only top level folders that have index.* file in them? This way everything except main widget files is hidden, and if there's a widget with sub-widgets in it (like my Sidebar), only the parent is shown.

I also have a semi-related comment: I think it would make sense to have these controls in a tab in Preferences window instead of dropdown menu. The latter is a bit of a usability minefield: it's not persistent enough to house so much important functionality, easy to miss it and close it by mistake, and it closes automatically as soon as user hits any menu item. My 2 cents :+1:

**Comment by felixhageloh** [comment]
Thanks for the feedback guys. I think maybe looking only one folder level deep could be a solution. I doubt that there are any widgets out there that are nested deeper than that (and if so they would be a few edge cases). 

About the status menu: I was also wondering wether I was stretching the intended use of dropdown menus. I was inspired by how Apple uses dropdown menus, for example for network and bluetooth 

![screen shot 2016-02-25 at 9 03 21](https://cloud.githubusercontent.com/assets/367503/13313524/ebd8a430-db9e-11e5-9bf8-c700156df5a6.png)

I feel like I'm just walking the line still, but if I were to add more functionality to it I'd have to consider using a preference window as you suggested. 
The advantages of using the menu are that it is only one click away and it is easy to build.

**Comment by felixhageloh** [comment]
@edasque it is not ideal but as a quick fix there are maybe two solutions: 
- if you are not relying on modules with native extensions, you could bundle them into a single script using [browserify](http://browserify.org). Bundled scripts would still show up as widgets but they would be only a few and not break the app anymore. 

- you can put them outside the widget folder and call them from your widgets using `/path/to/my/scripts/script.js`

**Comment by edasque** [comment]
Yes, I'll have to use (2) if you don't fix this quickly. Unfortunately that can't work with the widget I published, since they need to embed the scripts in the code. Right now, I stopped running it, unfortunately.

I don't think (1) is realistic with the many dozens of dependencies any module brings in.

**Comment by Pe8er** [comment]
> The advantages of using the menu are that it is only one click away and it is easy to build.

That is true :) However, let me offer a more visual inspiration. This is LaunchBar's action editor window, I think a similar layout would be perfect for Ubersicht:

![](http://imgur.com/Vdxc7vf.jpg)

I can't help you with coding but I'd be happy to whip up a design for you, if you decide to go down this route.

(also thank you for showing those orgasmic spiral wallpapers on Ubersicht website, found them and love them!!)

**Comment by felixhageloh** [comment]
@Pe8er if you feel like making a design mockup like this for Übersicht I'm always curious to see it :)!
Can't promise anything of course, but inspiration is always good

**Comment by Pe8er** [comment]
@felixhageloh alright, I'll be back with something next week.

**Comment by levifig** [comment]
Glad someone already reported this one… ;) 
![screen shot 2016-02-25 at 5 31 54 pm](https://cloud.githubusercontent.com/assets/1605/13336797/052907d0-dbe6-11e5-81a3-162808854dd7.png)

**Comment by edasque** [comment]
@felixhageloh , to close the loop, are you going to prioritize changing the depth of search to only 2 levels?

**Comment by felixhageloh** [comment]
@edasque @levifig what is a surprising to me still is that this behavior should not be new. The only thing that is new is that those scripts now show up in the widget list, but basically Übersicht already tried to parse these as widgets and threw errors in the past.
@levifig I actually suspect that your jquery problem is slightly different: I now include jquery via an npm module so it is only available as `$` and not as `jquery` anymore. It could be that your text fill jquery plugin accesses it as `jquery`. As I quick fix you can replace all uses of `jquery` with `$`. If that was the issue I can fix it in the next version.

About changing the official structure: it is a bigger decision since it changes the initial premise of the app, which was 'drop any coffee/js file you like and Übersicht will interpret it as a widget'. Of course people are now building more complex widgets and this initial design choice turns out to be hurting. So the only thing I want to avoid is rush into another (potentially) bad design choice. I think the solution you guys proposed is good, but basically I need some time to think it through. 

In the meantime you can work around the current limitations by:
- naming extra js libs `.js.lib` or any other file extension that doesn't end in .js or .coffee
- compiling js scripts into a single binary using browserify or [nexe](https://github.com/jaredallard/nexe) and removing the .js extension (as is common for binaries)
- moving scripts out of the widget folder as a last resort

To address you concern about browserify @edasque. It is actually quite common to compile large node apps in to a large bundle. The neat thing is that that it will only include what you are actually using. The downside is that you can't use native modules tho (which there aren't that many)

Anyway, these are just temporary solutions till I fix it from the other end, which might take a while still

**Comment by edasque** [comment]
@felixhageloh that's true, the issue isn't new. However the impact is / symptoms are. Now that the app displays every single thing it thinks is a widget in a list, that list becomes very large and the UI slows down (5000 entries or so for me) it becomes irresponsive. So it does initially display the widget but then crashes.

Do I take it you don't intent to fix it and continue to treat every JS or coffee file in the hierarchy as potential widgets?

**Comment by felixhageloh** [comment]
@levifig `window.jQuery` is available again in the version released today (0.8.35)

@edasque ok cool, I was just double checking wether I missed something. I do intend to fix this issue but I need some time to check and verify the solution. I will probably have to try many widgets from the widget gallery and make sure they keep on working before I can release a fix

**Comment by Pe8er** [comment]
> if you feel like making a design mockup like this for Übersicht I'm always curious to see it :)!
Can't promise anything of course, but inspiration is always good.

I cooked something up! How about I shoot it via email?

**Comment by felixhageloh** [comment]
hey sure! It's felix*dot*hageloh@gmail

**Comment by edasque** [comment]
How are we doing on this, @felixhageloh ?

**Comment by felixhageloh** [comment]
@edasque my current idea is to 
- ignore js files that are under `/node_modules/`
- ignore js files that are in a dir called `/src/` 

I believe this would solve your use case and has very low risk of breaking existing widgets. What do you think?

**Comment by levifig** [comment]
@felixhageloh This would be awesome!! One thing: I'm not sure `/src` makes sense though… `/includes` or `/modules` would make a bit more sense (since technically all of it is `src`… :P

**Comment by felixhageloh** [comment]
Also a bit unsure about the `/src` name ... it was inspired by a common node module source structure that you see:

```
/
| - src/
| - index.js
```

were most code lives in `/src` and `index.js` is the entry point for the module

**Comment by edasque** [comment]
That works for me. It seems many widgets also use a script directory

**Comment by edasque** [comment]
@felixhageloh is this something you're working on for the next release?

**Comment by felixhageloh** [comment]
Yup! I'm hoping it will be another big one: npm support + ES2015 + virtual DOM (like React)

**Comment by felixhageloh** [comment]
I'm finally nearing in on a new release! I've decided to leave out the Virtual DOM as a beta feature for now, but it does have support for CommonJs (require) and it does ignore files that are inside `/node_modules`, `/lib` and `/src`. This should fix this issue - anybody interested in beta testing?

**Comment by levifig** [comment]
@felixhageloh Fantastic news! I'd most definitely like to help test it so I can work on fixes/updates for my widget… :)

**Comment by felixhageloh** [comment]
here is a link to the beta https://www.dropbox.com/s/qq1oc4eohqw5frh/Uebersicht-0.9beta.app.zip

**Comment by levifig** [comment]
@felixhageloh Awesome! At first glance, it fixed all the issues with my widget! :D Now I can work on improving it… :)

**Comment by evanfuture** [comment]
I'll test too (tentatively).  Great work @felixhageloh !
