### ISSUE TITLE
[REQ] Fingbox Widget

### ISSUE THREAD

**Issue by hreality** [felixhageloh/uebersicht#202]
##Having issues with trying to get a widget to do network discovery using fingbox..
https://www.fingbox.com/help?c=command-line_tool&a=network_discovery

A geeklet (sorry bad word) already exists but the coding lang. is greek to me at present so any assist would be helpful..

Img (note upper right): http://www.macosxtips.co.uk/geeklets/modules/upload/attachments/Desktop14.jpg

Command (in geeklet): fing -r 1 --silent -o table,text,console --session ~/Documents/ThemeItems/networksession | awk 'NR>2{ print l} {l=$0}' | sed 's/.$//; s/^.//'

**Comment by felixhageloh** [comment]
does the command `fing -r 1 --silent -o table,text,console --session ~/Documents/ThemeItems/networksession | awk 'NR>2{ print l} {l=$0}' | sed 's/.$//; s/^.//'` work fine for you if you run it in the terminal? 
I have to use `sudo` to get it to work, which won't work for Übersicht because you have to provide a password

**Comment by hreality** [comment]
Yes sir

**Comment by felixhageloh** [comment]
`arp -a` might also give you something similar btw!
