### ISSUE TITLE
widget doesn't work after upgrade / update to 0.9 (38)

### ISSUE THREAD

**Issue by badummtss** [felixhageloh/uebersicht#203]
I update übersicht and using the weather.widget. after upgrade all widgets working fine except of weather.widget...
what is the problem? in the debug console under elements no weather.widget is under any div - container....
pls help

**Comment by felixhageloh** [comment]
It should be fixed now - you can try re-downloading the widget to get the latest version! Please let me know if it works for you

**Comment by badummtss** [comment]
Yes it is working now, can you explain, in short sets, what the problem was?

**Comment by felixhageloh** [comment]
sure! the widget was using `"#{process.arg[0]}"` inside the command string, to get a path to the node binary that ships with Übersicht. This used to work because the node process would eval the widget, so process.argv[0] was set correctly. Now I use [browserify](http://browserify.org) for making modules work, which means the widget source doesn't get evaled by the node process anymore. 

The fix was to use a shell command that figures out the parent process name _at runtime_. (`ps -o comm= $PPID` plus some code to deal with the umlaut, in case you are interested)

**Comment by badummtss** [comment]
Ok sounds complicated, i understand how i have to use the files which are coming with the widgets.
mostly i understand only the web based thing in the files. 
Do you talk german? because of the word umlaut and perhaps "übersicht" is definitively a german word i know.
Because of the umlaut thing, i thought ever this is a character set problem e.g. UTF etc., i never know that this ist so complex to deal with it.

**Comment by felixhageloh** [comment]
yeah I'm German originally :)

**Comment by badummtss** [comment]
Super würd gern mal ne runde mit dir quatschen XD

**Comment by felixhageloh** [comment]
hey klar! Über chat oder Skype oder so?

**Comment by badummtss** [comment]
wie du magst, sorry das ich jetzt erst schreibe XD (prüfungsstress). glaub hab alles da, falls nicht ist das auch nicht das thema...

**Comment by felixhageloh** [comment]
kein Problem - ich hab z.zt. auch viel um die Ohren :). Ich bin auf GoogleTalk zu finden: felix.hageloh@gmail.com
