### ISSUE TITLE
Widgets not working after upgrade to 0.9.39

### ISSUE THREAD

**Issue by miccal** [felixhageloh/uebersicht#204]
I use the "Simple Keyboard/Mouse Stats" widget and the "Daily Background Wallpaper" widget, neither of which work after upgrading to 0.9.39. I have attached the screenshots from the debug console.

![screen shot 2016-05-26 at 08 43 30](https://cloud.githubusercontent.com/assets/6127163/15560475/818a0610-231e-11e6-822f-0d696816a6c1.png)
![screen shot 2016-05-26 at 08 44 23](https://cloud.githubusercontent.com/assets/6127163/15560476/81df96ac-231e-11e6-9f45-f97238b522b9.png)

Thanks for the great app.

**Comment by felixhageloh** [comment]
ah yes, that's an annoying one - I've upgraded to the latest version of coffeescript and it turns out to be a lot stricter. This one might actually be a CoffeecScript bug but I'm not 100% sure. Luckily there is a workaround:

Inside the command string look for `\1` (near the end) and replace it with `\#{1}`. I've also made a PR for this widget so if the owner has merged it in you can also just re-download the widget and it should include the fix.

**Comment by miccal** [comment]
Thanks, that fixed the "Daily Background Wallpaper" widget. Any thoughts on the error with the "Simple Keyboard/Mouse Stats" widget?

**Comment by felixhageloh** [comment]
ah sorry read to fast and didn't notice the second issue!
You can see the fix here https://github.com/Paradiddley/Simple-Uber-Device-Status/pull/2/files, i.e. you need to remove all the `@`s in front of style

**Comment by miccal** [comment]
All fixed, thanks!
