### ISSUE TITLE
Updates are sequential rather than the most recent

### ISSUE THREAD

**Issue by joecreighton** [felixhageloh/uebersicht#205]
I was running 0.8 and was prompted to update.  That got me to 0.9(39) which immediately threw up another update prompt for 0.9.40.  It's not game breaking but adds unnecessary steps.

This also happened to me in the past but I was very new to Ubersicht and github so (not knowing what to do with the information) I left it alone.  Since it has returned, here's a new Issue for you!  :)

**Comment by felixhageloh** [comment]
Interesting - thanks for reporting. It is a bit out of my hands, since I'm using a library to handle automatic updates. I'll keep an eye on it and see if there is a setting or if a newer version of the library fixes it. 
At least there is a small advantage - this way people see all the release notes of what is new and not just the latest one :).

(Aware of this now so I'm, closing the issue)
