### ISSUE TITLE
Widgets can't connect to internet using USB LAN adapter

### ISSUE THREAD

**Issue by exislow** [felixhageloh/uebersicht#206]
I have a MacBook Air (mid 2012) with a AX88179 USB 3.0 to Gigabit Ethernet adapter which is working great! I have not experienced any problems until now.

Übersicht has four widgets installed (Battery, Calendar, Pretty Weather, Authentic Widget). Those two weather widgets, which need an internet connectivity refuse to make any internet calls while I am on LAN. As soon as I switch my LAN off and use the built-in WiFi everything works fine.

Any solution for this?

**Comment by felixhageloh** [comment]
strange! Two things that might help to debug:
- can check the debug console and post any errors here 
- can you try to run this in the terminal while connected your LAN and post the result here?
```sh
curl www.google.com
```

**Comment by exislow** [comment]
The debug console has no errors. `Console`Tab is empty. Network tab see here:
[https://abload.de/img/bildschirmfoto2016-05jqsvm.png](https://abload.de/img/bildschirmfoto2016-05jqsvm.png)

`curl` works fine on my Mac

```
$ curl www.google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.de/?gfe_rd=cr&amp;ei=emdMV9qgK-aA8QeulqqYDw">here</A>.
</BODY></HTML>
```

Any other suggestions?

**Comment by felixhageloh** [comment]
cool, thanks so we can rule that out. I also though that these widgets were using `curl` but that's actually not the case. Looking at the code revealed another potential point of failure tho: It is probably an issue with geolocation. AFAIK, OS X needs wifi in order to be able to figure out your location. Being connected via an ethernet cable should be fine as long as your wifi is also enabled. However, if your wifi is switched off completely I'd expect it to not work. Is that the case for you?

**Comment by exislow** [comment]
My WiFi was disabled while I use LAN. That is the error! As soon as I additionally enabled WiFi the weather plugins working. Thus, no connectivity issue, but a location problem. Thank you a lot!

**Comment by felixhageloh** [comment]
glad I could help out!
