### ISSUE TITLE
Clickthrough prevented to Path Finder Desktop

### ISSUE THREAD

**Issue by gregoj** [felixhageloh/uebersicht#217]
I recognize this is related to another app, but it bears understanding since it is breaking global functionality. This appears to have arisen since the most recent update, 1.0 (42).

Path Finder (cocoatech.com) is a common Finder replacement. When übersicht is running clicks to the Desktop do not bring Path Finder to the front as it does when übersicht isn't running. Clickthrough to Finder's desktop works correctly.

Again this did not happen with previous versions. I'm happy to debug on this side, but to date I've not been able to discern the issue.

**Comment by roadglide03** [comment]
I am seeing the same thing.  Also when you double click on one of the widgets running it produces a shadow box.

**Comment by kbecker87** [comment]
same here, can’t use Übersicht now which is pretty sad…

**Comment by felixhageloh** [comment]
sorry to hear guys! I have a beta version that looks like it fixes the issue: https://dl.dropboxusercontent.com/u/49351082/%C3%9Cbersicht-beta.app.zip

Not sure if it is releasable tho - I remember this approach caused issues on some older OS X versions, but since 10.9 is not supported anymore, it might be ok now. 

Please give it a spin and let me know if you encounter any issues!

**Comment by kbecker87** [comment]
Thanks Felix for your fast help! I’m testing your beta build and as of now it seems to work fine. I’m able to run Übersicht and use my Pathfinder Desktop. Thanks!

**Comment by felixhageloh** [comment]
released today as part of version 1.0.43

**Comment by felixhageloh** [comment]
I had to revert this fix since it was causing other issues (Issue #229 and #231 ). However, I've made it available as an option: in preferences you can enable 'Compatibility Mode'. It has the same bugs as mentioned above, but if you didn't encounter those it might be an acceptable option for you. 
It is a workaround for now, but I couldn't come up with a better solution yet
