### ISSUE TITLE
Mavericks support quietly dropped?

### ISSUE THREAD

**Issue by jwilliams108** [felixhageloh/uebersicht#218]
It seems that your latest update (1.0.42) has quietly dropped support for 10.9.5? As well, on my other machine that runs 10.11.5, the font rendering has become noticeably poorer with the new version.

**Comment by felixhageloh** [comment]
Mavericks support was indeed dropped, because the latest web view which 1.0.42 introduced is not available on Mavericks. My intention was not to drop it quietly - it was mentioned in the release notes, but maybe I could have been more explicit about it. 

About font rendering: AFAIK nothing should have changed there, but it could be that the latest web view behaves differently. In any case, you can control font rendering in tour widgets by using the `-webkit-font-smoothing` property (http://maxvoltar.com/sandbox/fontsmoothing/)

**Comment by felixhageloh** [comment]
out of curiosity, how did the font smoothing change?  I have subpixel antialiasing disabled globally on my mac, which is probably why I didn't see a difference. Was it subpixel antialiased before and now it it is grayscale antialiased (or not at all) or the other way round?

**Comment by jwilliams108** [comment]
It looks like it is not antialiased by default at all, adding `-webkit-font-smoothing: subpixel-antialiased` has fixed it though. Thanks!
