### ISSUE TITLE
Using 'run' with JSX syntax

### ISSUE THREAD

**Issue by motleydev** [felixhageloh/uebersicht#254]

**Comment by motleydev** [comment]
I'm trying to figure out the nuances of the JSX format since I'm less inclined to learn coffeescript if I don't have to. :)

However I have this sample widget that should in theory use the plain javascript @run method to update an element afterRender, but nothing is happening.

```
const d3 = require('d3');
const run = require('run');

export const command = "echo Hello World!";

export const refreshFrequency = 5000;

const style = {
    marginLeft: 20,
    marginTop: 20,
    color: '#ffffff',
}

export function render(output) {
    return <div style={style} id="app">test</div>
}

export function afterRender(domEl) {
    
    run('echo test2', (error, stdout) => {
        $(domEl).find('#app').text(stdout)
    })
}
```

**Comment by felixhageloh** [comment]
These JSX widgets work quite differently from the 'classic' widgets. There are a few main concepts 
- they are using a virtual dom with a diffing algorithm (like React). This means we can just call render every time something changes, because it won't re-create the entire DOM and just update what is necessary. Thus there is no need for an `update` method. Also we can't manipulate the DOM directly anymore, so also no need for an `afterRender` method
- widgets are now stateless. If you are familiar with React, they are like stateless functional components. 
- state is managed outside the widget in a Redux-like state container. State can only be updated in 'reducers' as a response to actions. The reducer function for a widget is the `updateProps` function (you can see it in action here https://gist.github.com/felixhageloh/94d5dd41cc5ff8a633900ffb28bd195a). It gets passed the previous state (props) and the current action.  Whatever it returns is considered the current state and is passed to the `render` function. By default, whenever a command runs, the following action gets dispatched `{ type: 'UB/COMMAND_RAN', error: err, output: output }`, where `output` is the command  output and `error` contains errors, if any.

**Comment by felixhageloh** [comment]
To continue from my previous comment, to trigger custom actions you have to use the `dispatch` function, which is passed to `render`. So to get something running like in your example, you would have to do something like

```jsx
const run = require('run');

export const command = "echo Hello World!";

export const refreshFrequency = 5000;

const style = {
    marginLeft: 20,
    marginTop: 20,
    color: '#ffffff',
}

export function updateProps(prev, action) {
  return action.output;
}

export function render(output, dispatch) {
    run('echo test2', (error, stdout) => {
       dispatch({type: 'MY_CUSTOM_ACTION', output: stdout, error: error});
    })
  return <div style={style} id="app">test</div>;
}
```

However, _this will end up in an endless loop_. Every time you render you will dispatch a new action, which will trigger render again and so on. The idea behind dispatching custom actions is to do it in event handlers (onclick etc) or as a response to specific state changes. So for example you could do

```jsx
const run = require('run');

export const command = "echo Hello World!";

export const refreshFrequency = 5000;

const style = {
    marginLeft: 20,
    marginTop: 20,
    color: '#ffffff',
}

export function updateProps(prev, action) {
  return action.output;
}

export function render(output, dispatch) {
  return <div 
    style={style} 
    on-click={[dispatch, {type: 'MY_CUSTOM_ACTION', output: stdout, error: error}]}>
      test
    </div>;
}
```

**Comment by felixhageloh** [comment]
(also closing this, but as before, feel free to continue the conversation)
