### ISSUE TITLE
Refresh rate going crazy

### ISSUE THREAD

**Issue by motleydev** [felixhageloh/uebersicht#255]
I have a render and an afterRender method in a coffeescript file. If I have a refreshFrequency set it flickers an svg element created (via d3) in the afterRender method. It was my understanding that should be updated during an "update" cycle?

If I remove the refreshFrequency it suddenly starts attempting to update about every half second.

```coffeescript
d3 = require('d3');

refreshFrequency: 5000

render: () -> '<div id="app"></div>'

afterRender: (domEl) ->
    @run("", (error, stdout) ->
        svg = d3.select('#app').append('svg').attr('width', 1000).attr('height',900)
        svg.append('circle').attr('cx', 20).attr('cy', 20).attr('r', 20)
    )

style: """
    left: 20
    top: 20
    color: #fff
"""
```

**Comment by motleydev** [comment]
so it seems that I need to call @stop() after the @run() command - is that correct? Seems like the @run declaration should adhere to whatever context it's being called in (ie, in an update, afterRender or other)

**Comment by felixhageloh** [comment]
I don't follow 100% but maybe this will give some clarity:

`render` replace the _entire_ dom every time, which is why you see some flickering. If you want to add something to the dom without replacing it you want to call the update method. 
I also don't quite see why you are calling @run, since you are not executing any command. Also, from this example there seems to be no need to refresh the widget, since it only renders a static svg, right?

Assuming all this, I think what you are looking for is something like this:

```coffeescript
d3 = require('d3');

refreshFrequency: false # don't refresh

render: () -> '<div id="app"></div>'

update: (_, domEl) ->
  svg = d3.select(domEl).append('svg').attr('width', 1000).attr('height',900)
  svg.append('circle').attr('cx', 20).attr('cy', 20).attr('r', 20)

style: """
    left: 20
    top: 20
    color: #fff
"""
```

**Comment by felixhageloh** [comment]
(closing this issue btw, but feel free to continue the conversation)

**Comment by motleydev** [comment]
So the issue is that the refresh rate was not the `5000` that I set, but every second or so. I intend to render a static svg in the afterRender and then do some update magic (like moving the hands on a clock or something) in an update call. I used the @run because it wasn't working for me without it. :) Am I missing something there? Is that due to the d3 call being in the "afterRender" instead of update call?

so, 2 issues:

1. Refresh was every 1000 (or less?) instead of 5000
2. I needed to use @run in the "afterRender" call otherwise it didn't do anything

**Comment by felixhageloh** [comment]
I think I understand the issues you were seeing, but they don't match with the code you posted here. My best guess is that you had some interference form another widget. In particular, this kind of thing
```
d3.select('#app')
```
is something you should avoid, because it is not scoped to your widget. It finds all dom elements with the id 'app', so not only the ones in your current widget. This means if you have another widget running that does the same, the two will interfere with each other.

**Comment by motleydev** [comment]
Thanks for the responses! I only have one widget though. If I add the @stop() command, it stops the crazy refresh rate.

**Comment by felixhageloh** [comment]
what about the version I posted here. Does that work?

**Comment by motleydev** [comment]
So I finally got a chance to try it! Your method does work, but I don't know if your's working totally explains why mine wasn't - was I actually doing something wrong?
