### ISSUE TITLE
widgets containing iframes https support

### ISSUE THREAD

**Issue by bauen1** [felixhageloh/uebersicht#264]
Would require ```X-Frame-Options``` to be set to ```ALLOWALL``` which might be insecure

**Comment by felixhageloh** [comment]
isn't this the case for http as well?

**Comment by bauen1** [comment]
I'm not entirely sure to be honest, some sites work, whilst others don't.
For example youtube as embedded video player works.

Works ™
```
<iframe width="800" height="500" src="//www.youtube.com/embed/ILt5HZnPz5o?version=3&autoplay=1&loop=1&controls=0&showinfo=0" frameborder="0" allowfullscreen></iframe>
```
Doesn't Work ™
```
<iframe width=800" height="500" src="//reddit.com/r/unixporn"></iframe>
```

**Comment by felixhageloh** [comment]
Exactly, it is the remote site that disallows being iframed. It looks like there might be a workaround https://github.com/electron/electron/issues/426

**Comment by Porco-Rosso** [comment]
I hadn't noticed since for some reason my ubersicht wasn't finding updates...
 but upon updating to a newer version all my widgets making use of iframes have stopped working .

Here is the error in the console using this simple [widget](https://github.com/Porco-Rosso/Ubersicht-Matrix)
`Refused to display 'http://127.0.0.1:41416/matrix.widget/Matrix.html' in a frame because it set 'X-Frame-Options' to 'deny'.`

Since iframes are a useful way to quickly add interesting web content it would be great to find a workaround. (maybe limit to 127.0.0.1 if security is a concern?)

**Comment by felixhageloh** [comment]
@Porco-Rosso if I understand correctly, you are framing a static HTML page from within your widget folder?

As a security measure I disallow iframing of Übersicht itself. However, external sites (that allow you to iframe them) should work fine.

I will allow 'sameorigin' in the next release which should fix your use case again.

**Comment by felixhageloh** [comment]
'X-Frame-Options' is now set to sameorigin. Let me know if this works for you @Porco-Rosso

**Comment by Porco-Rosso** [comment]
Yes that is indeed what I am doing. Just tested the newest release ([1.4.59](https://github.com/felixhageloh/uebersicht/releases/tag/1.4.59)) and it works fine now. Thanks for the quick fix!
