### ISSUE TITLE
Question: how to make multiple AJAX requests?

### ISSUE THREAD

**Issue by Offbeatmammal** [felixhageloh/uebersicht#268]
forgive the newbie question...
I've worked out how to get a single JSON response using the command with curl but, the widget I'm trying to build needs me to make a series of requests for data (and I can't easily chain them on the single command because there's some logic in the flow) but ... I can't work out how to make ajax requests from within the update block to gather the data I need to build the output...
is there an idiots guide, or a widget that does that I could crib from?

**Comment by felixhageloh** [comment]
No worries :)
I think you best bet is to write a node script that does all your requests (in sequence) and then prints the result to stdout. You can then call this script as your command.
You could also do the ajax calls directly from your widget (by using a function instead of a string as your command), but it might get more complex because of CORS issues - support for that will come in the next release tho

**Comment by felixhageloh** [comment]
closing this, because it is a question, but feel free to follow up if you need more details!
