### ISSUE TITLE
High CPU load with CSS animation

### ISSUE THREAD

**Issue by philiprenich** [felixhageloh/uebersicht#303]
Hi, I have a widget that is performing a simple `curl` request to get ~6.7kb of data and parsing that to show the results. The refresh rate is set to `refreshFrequency: '5m'` so it's pretty calm. However, I've found it to be a major energy hog by disabling it. Digging into the code, if I turn off a CSS animation, it runs fine. I have a small little `<div>` as a line that shrinks it's height down to 0 as a sort of hourglass countdown until the next refresh. 

I decided to use a CSS animation rather than JS because I figured that would be much more lightweight. Is there something in the constant rendering of this that causes a big slowdown and CPU/energy usage?

**Comment by felixhageloh** [comment]
So you are saying without CSS animations you don't see high CPU usage?

**Comment by philiprenich** [comment]
That’s correct

**Comment by felixhageloh** [comment]
CSS animations should have the same performance as they do in Safari. You can verify this by opening the debug console and typing `window.location.href` and then open the link you see in Safari. If Safari seems to have a much lower CPU usage, please let me know!

One general tip that might help: animating the height of a DOM element can be quite expensive, because it will trigger a layout on every step. If you can, try using a css transform; for example `transform: scale(x, y)`. It should be a lot more performant
