### ISSUE TITLE
White background on errored widgets

### ISSUE THREAD

**Issue by drisc** [felixhageloh/uebersicht#360]
When a command fails an inline style is applied, I know that the command will fail (cmus-remote being run when cmus isn't running). Is there a way to remove the styling?

Screenshot: ![Screenshot 2019-03-28 at 11 09 33 pm](https://user-images.githubusercontent.com/2449110/55200111-9ce92900-51b4-11e9-84a7-75df5c815b86.png)

**Comment by felixhageloh** [comment]
I'm assuming you are using the old CoffeeScript syntax. I have not build in a way to customize the error styling, but you can provide your own error handling. 

instead of using a command string like 
```coffeescript
command: "curl http://example.com"
```

You can use a function:

```coffeescript
command: (callback) ->
  @run("curl http://example.com", (error, output) -> callback(null, output))
```

This will completely ignore error and pass `undefined` as output to the render/update function when an error occurs. You can also pass the error to you render function like:

```coffeescript
command: (callback) ->
  @run "curl http://example.com", (error, output) -> 
    callback(null, error ? error : output)
```

and then check whether `output` is of type Error inside your render/update functions. That way you can render the error message with custom styling. 

The latest jsx syntax for widgets has better error handling built in by default, so I would recommend switching to that.

**Comment by drisc** [comment]
Yes, I'm using CoffeeScript still. This has fixed the styling issue but I'll take your advice and update my widgets to JSX.

Thanks for the help!
