### ISSUE TITLE
Cannot Access Desktop After Update to 1.5 

### ISSUE THREAD

**Issue by robertdefilippi** [felixhageloh/uebersicht#417]
Hello,

I just updated to uebersicht Version 1.5 (62)

My widgets still work, but I can no longer can click any of the files or folders on my desktop, or use the drag to select window. I can still access the files through Finder, just not on the desktop directly. It seems that my clicks are not being registered when I'm trying to access anything on the desktop.

 I'm not sure how to debug this, so any assistance would be great.

Thanks,

**Comment by Wilaby** [comment]
Hey, I also encountered this issue. I believe it is because the preference to assign a command key was removed and interaction was meant to be without a command with the most recent update. Hopefully the option to add a command key to interact will be re-added.

**Comment by felixhageloh** [comment]
Hi, do you have a widget that covers the entire desktop by any chance (even if transparent)? You can use the debug console to double check that. 

Since 1.5 widgets are always clickable and are 'on top' of items on the desktop. This means that if a widget overlaps an item on your desktop, only the widget will be clickable. However, any empty space should remain clickable for desktop items. 

As a quick fix you can also disable interaction entirely (inside Preferences)

**Comment by Wilaby** [comment]
Yes my widget fully covers the desktop, how could would I go about using the desktop normally if it fully covers. (Without disabling interaction entirely)

**Comment by felixhageloh** [comment]
Alright, so luckily it does not sound like a bug 😅 

You have a few options:
- make your widget ignore mouse events (using CSS `pointer-events: none`)
- make sections of your widget ignore mouse events (using the same method)
- size your widget to only use the space it needs. So for example, instead of using `width: 100%; text-align: center` to center align content, use other techniques if possible (flex-box, auto margins etc)

**Comment by robertdefilippi** [comment]
Ah, I now see what the issue was. The suggestions fixed my issue. Thanks @felixhageloh
