### ISSUE TITLE
Refreshing widget causing intervals in code to speed.

### ISSUE THREAD

**Issue by darkjuanjo** [felixhageloh/uebersicht#449]
I  have a timer that updates every second to change an image and the data displayed.( I am using a  refresh frequency of 3 seconds and a setinterval of 1 second).
However if I make any change in the code and then refresh the widget the setintervals start adding up speeding up the timers.

Is there a way to refresh and clear all the interval to prevent the intervals from adding up?

**Comment by upstageleft** [comment]
if ( typeof intervalVar != 'undefined' ) clearInterval(intervalVar);

**Comment by darkjuanjo** [comment]
@upstageleft thank you for your help.
I tried as you suggested but unfortunately didn't work.
`if(typeof Timer != undefined)
clearInterval(Timer);
var Timer = setInterval(animation, 300);`

**Comment by upstageleft** [comment]
The test for Timer needs to have "undefined" in quotes, because typeof returns a string value. You probably ought to use 
```
( typeof Timer !== "undefined" )
```
(Single vs. double quotes shouldn't matter. Operator is a bang and double equals !== which tests type as well as value.  != only tests value.)

Last, don't use the 'var' keyword since 'var' tells the parser to define the variable within the local scope, and for this you want global to make sure you're testing the same variable the next time around without having to worry about embedding it in a closure.

**Comment by darkjuanjo** [comment]
@upstageleft Thank you! 
This seems to work! 
`if(typeof Timer !== 'undefined')
clearInterval(Timer);
window.Timer = setInterval(animation, 300);`
