### ISSUE TITLE
Major performance issues on Big Sur with simple-bar

### ISSUE THREAD

**Issue by issmirnov** [felixhageloh/uebersicht#450]
I'm running a 2019 16" MBP (2.4Ghz i9, 32gb RAM) with https://www.simple-bar.com/en/.

I have noticed major regressions after upgrading to Big Sur. The entire system slows to a crawl, to the point that even opening a new Google Chrome tab is unbearable slow and takes 5-8 seconds.

I'm running dual 2k 27" monitors, connected via a RX 570 through a Razer Core X Chroma GPU. Issue appears to be worse when the monitors are connected.

I'm not sure if this is due to simple-bar or ubersicht itself. I do notice that the Activity Monitor shows Ubersicht as using 80+ energy impact, with Chrome using about 90. This is surprising, as the bar has a notification event model rather than polling.

**How can I help debug this?**

**Comment by trankien386** [comment]
Have you ever considered opening this issue on simple-bar repository? I'm having the same issue on macOS 11.2.1.

**Comment by issmirnov** [comment]
I have one for Yabai here: https://github.com/koekeishiya/yabai/issues/892

Good point about simple-bar. I thought I had opened one, but I must have lost the draft. I'll update here when I have time to copy my message above to their issue tracker.

**Comment by felixhageloh** [comment]
Hi there! Do the performance issues stop when quitting Übersicht?

**Comment by trankien386** [comment]
@felixhageloh It's more like a simple-bar's issue rather than Übersicht's I think. I used Übersicht with a weather widget and [snowflakes](https://github.com/theLMGN/uebersicht-snowflakes) and CPU usage always at about 6%. When I started to use simple-bar, up and down like crazy CPU graph go. The computer is acceptably usable if you do light web browsing but when it's coming to heavy apps, I can't imagine the lag.

At the end of the day, it feels like an aesthetic gimmick without any practical benefits. I don't want my desktop to be good-looking at the cost of performance, so I prefer to not using it anymore.

**Comment by issmirnov** [comment]
I would agree with this. Previously I was using a different, homemade bar and performance wasn't an issue. I opened https://github.com/Jean-Tinland/simple-bar/issues/141 to flag this. 

Closing this one, as the problem is not with uebersicht itself.

Thanks all for your input! Please chime in on https://github.com/Jean-Tinland/simple-bar/issues/141 if you have additional thoughts.
