### ISSUE TITLE
Message widget

### ISSUE THREAD

**Issue by entropitor** [felixhageloh/uebersicht#454]
Is it possible to send a message to a widget? I know there is applescript to do a full reload but is there anything else? 

E.g. using applescript or something like hammerspoon or can we listen to a unix socket?

**Comment by hypersun-pro** [comment]
I'm not an expert on this, but a trick I can think of is to use node socket server. Create a socket server, and use the run function(assuming you're using jsx) to start the server. The widget should connect to the server and receive any socket message from the server. Since node is a server, you can make it so it also listen for any Http request and sends message to the widget to the server. Here's a short summary:
Http GET request ⇒ node server ⇒ Widget socket client
Downside: I'm not sure how much of a performance issue that will cause, and it's a lot of coding to create a server just to do the messaging. If there's any alternative, I suggest trying the other one.

**Comment by entropitor** [comment]
Okay, thanks!
