### ISSUE TITLE
~/.bash_profile is clearly for bash

### ISSUE THREAD

**Issue by droukd** [felixhageloh/uebersicht#83]
what should we use to let's say set (export) BLOCKSIZE.

**Comment by felixhageloh** [comment]
I think your best bet is to write a little shell script (or just inline the `export`s) and run that as your command. I'm not entirely sure which env mac apps get executed in, but it is definitely not you standard terminal env, which is why setting variables in ~/.bash_profile, ~/.bash_login, ~/.bashrc doesn't work

**Comment by felixhageloh** [comment]
You could also try a `source ~/.bash_profile & ...` before your command

**Comment by deanishe** [comment]
FWIW, the environment your script gets executed in is probably the same as Übersicht's, which is in all likelihood almost empty, as it was probably started via `launchd`. There'll be `LC_TYPE=C` and not much else.

To get your shell environment, you have to start the app binary within the app bundle directly from your shell.

**Comment by felixhageloh** [comment]
thanks @deanishe - that makes sense! Commands are executed inside a node process which is spawned by Übersicht, so I would expect it to have the same env as well. 
Btw I read that you can set env vars for mac gui apps in `/etc/etc launchd.conf` so these would probably be available.
